stages:
  - release

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Releasing version $CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG  
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "Automatisch erstelltes Release für $CI_COMMIT_TAG"
